### ISSUE TITLE
ValueError: no signature found for builtin <built-in method tensor of type object at 0x7f37fc71a460>

### ISSUE THREAD

**Issue by nevergone123** [prs-eth/Dynamic-LiDAR-Resimulation#3]
I tried to run the training and got this error.
The env setup is totally the same: Python 3.10.10, PyTorch 1.13.1, CUDA 11.6.
How can I fix it?

(dynfl) root@admin:~/AImodel/Dynamic-LiDAR-Resimulation# ns-train NFLStudio --pipeline.datamanager.dataparser-config.context_name 10061305430875486848_1080_000_1100_000 --pipeline.datamanager.dataparser-config.root_dir WaymoPreprocessing/processed_data_dynamic --experiment_name 10061305430875486848_1080_000_1100_000
Loaded compiled 3D CUDA chamfer distance
/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py:341: UserWarning: The field pipeline is annotated with type <class 'nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig'>, but the default value NFLPipelineConfig:
    _target: <class 'NFLStudio.nflpipeline.NFLPipeline'>
    datamanager: NFLDataManagerConfig:
        _target: <class 'NFLStudio.datamanager.NFLDataManager'>
        data: None
        camera_optimizer: None
        masks_on_gpu: False
        images_on_gpu: False
        dataparser_config: NFLDataParserConfig:
            _target: <class 'NFLStudio.dataparser.NFLDataParser'>
            data: .
            context_name: 1005081002024129653_5313_150_5333_150
            root_dir: /scratch/hanfeng/LidarSimStudio/processed_data_dynamic
            min_near: 2.75
            max_dist: 75
            scene_size: 50
            min_inc: -17.6
            max_inc: 2.4
            width: 64
            height: 2650
            extra_margin: 10.0
            shift: [1.5, 1.5, 0.5]
            fp16: True
            normalize: True
        train_num_rays_per_batch: 4096
        shuffle: True
        num_workers: 8
        eval_num_rays_per_batch: 4096
    model: NFLModelConfig:
        _target: <class 'NFLStudio.nflmodel.NFLModel'>
        enable_collider: True
        collider_params: {'near_plane': 2.0, 'far_plane': 6.0}
        loss_coefficients: {'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0}
        eval_num_rays_per_chunk: 4096
        prompt: None
        encoding_sdf: HashGrid
        encoding_dir: SphericalHarmonics
        activation: relu
        per_level_scale: 1.6
        device: cuda:0
        center: None
        extent: None
        num_vehicles: 0
        aabb_vehicle: []
        tsfm_vehicle_train: None
        tsfm_vehicle_eval: None
        save_dir: ./save_dir/
        loss: {'d_url': 3.0, 'clamp_eps': 0.01, 'reweight': True, 'eikonal': 0.3, 'sdf': 1.0, 'surface_sdf': 3.0, 'depth_vol': 3, 'i_l2': 50.0, 'rdrop_bce': 0.15, 'rdrop_ls': 0.15}
        datamanager_config: NFLDataManagerConfig:
            _target: <class 'NFLStudio.datamanager.NFLDataManager'>
            data: None
            camera_optimizer: None
            masks_on_gpu: False
            images_on_gpu: False
            dataparser_config: NFLDataParserConfig:
                _target: <class 'NFLStudio.dataparser.NFLDataParser'>
                data: .
                context_name: 1005081002024129653_5313_150_5333_150
                root_dir: /scratch/hanfeng/LidarSimStudio/processed_data_dynamic
                min_near: 2.75
                max_dist: 75
                scene_size: 50
                min_inc: -17.6
                max_inc: 2.4
                width: 64
                height: 2650
                extra_margin: 10.0
                shift: [1.5, 1.5, 0.5]
                fp16: True
                normalize: True
            train_num_rays_per_batch: 4096
            shuffle: True
            num_workers: 8
            eval_num_rays_per_batch: 4096 has type <class 'NFLStudio.nflpipeline.NFLPipelineConfig'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py:1038: UserWarning: Mutable type <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> is used as a default value for `datamanager`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.data.datamanagers.base_datamanager.DataManagerConfig'> as frozen.
  warnings.warn(
/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py:1038: UserWarning: Mutable type <class 'nerfstudio.models.base_model.ModelConfig'> is used as a default value for `model`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.models.base_model.ModelConfig'> as frozen.
  warnings.warn(
/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py:1038: UserWarning: Mutable type <class 'NFLStudio.datamanager.NFLDataManagerConfig'> is used as a default value for `datamanager`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'NFLStudio.datamanager.NFLDataManagerConfig'> as frozen.
  warnings.warn(
/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py:1038: UserWarning: Mutable type <class 'NFLStudio.nflmodel.NFLModelConfig'> is used as a default value for `model`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'NFLStudio.nflmodel.NFLModelConfig'> as frozen.
  warnings.warn(
Traceback (most recent call last):
  File "/root/miniconda3/envs/dynfl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 263, in entrypoint
    tyro.cli(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_cli.py", line 378, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 116, in from_callable_or_type
    field_out = handle_field(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 312, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 525, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 116, in from_callable_or_type
    field_out = handle_field(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 312, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_parsers.py", line 465, in from_field
    default_name = _subcommand_matching.match_subcommand(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 44, in match_subcommand
    typetree = _TypeTree.make(type(default), default)
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 83, in make
    {
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 84, in <dictcomp>
    field.intern_name: _TypeTree.make(field.type_or_callable, field.default)
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 83, in make
    {
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 84, in <dictcomp>
    field.intern_name: _TypeTree.make(field.type_or_callable, field.default)
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_subcommand_matching.py", line 75, in make
    typ, _type_from_typevar, field_list = _fields.field_list_from_callable(
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py", line 281, in field_list_from_callable
    field_list = _try_field_list_from_callable(f, default_instance)
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py", line 459, in _try_field_list_from_callable
    return _try_field_list_from_general_callable(f, cls, default_instance)
  File "/root/miniconda3/envs/dynfl/lib/python3.10/site-packages/tyro/_fields.py", line 915, in _try_field_list_from_general_callable
    params = list(inspect.signature(f).parameters.values())
  File "/root/miniconda3/envs/dynfl/lib/python3.10/inspect.py", line 3254, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/root/miniconda3/envs/dynfl/lib/python3.10/inspect.py", line 3002, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/root/miniconda3/envs/dynfl/lib/python3.10/inspect.py", line 2468, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/root/miniconda3/envs/dynfl/lib/python3.10/inspect.py", line 2275, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in method tensor of type object at 0x7f37fc71a460>

**Comment by hanfeng-wu** [comment]
looks like a data class problem, I have fixed it in the commit [training bug fix](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/commit/1b5a4787cce77dafb0f087c14adc1addbb4a76fb). you can pull the latest commit to test it.
