### ISSUE TITLE
cfg Error

### ISSUE THREAD

**Issue by cqf7419** [prs-eth/Dynamic-LiDAR-Resimulation#8]
Loaded compiled 3D CUDA chamfer distance
Traceback (most recent call last):
  File "/miniconda/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/miniconda/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/miniconda/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 731, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/miniconda/lib/python3.8/site-packages/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/miniconda/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/miniconda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/usr/lansheng/Dynamic-LiDAR-Resimulation-master/DyNFL/NFLStudio/my_config.py", line 7, in <module>
    from NFLStudio.nflpipeline import NFLPipeline, NFLPipelineConfig
  File "/data/usr/lansheng/Dynamic-LiDAR-Resimulation-master/DyNFL/NFLStudio/nflpipeline.py", line 16, in <module>
    class NFLPipelineConfig(cfg.InstantiateConfig):
NameError: name 'cfg' is not defined

hello authors, how should i solve this error??   @hanfeng-wu 
I suspect it is a version problem with nerfstudio. Can you tell me the version number you are using?

**Comment by hanfeng-wu** [comment]
Hi, the version number is documented in the README: Python 3.10.10, PyTorch 1.13.1, CUDA 11.6, Nerfstudio 0.3.4, GeForce RTX 3090/GeForce GTX 1080Ti

I think you are also not using the correct python version, I would suggest to follow the README to setup the environment.
